version: '3'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    mem_limit: 500m
    restart: always
    ports:
      - 27000:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
      - MONGO_INITDB_DATABASE=root-db
    volumes:
      # seeding scripts
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # named volumes
      - ./mongo/data/db:/data/db
      - ./mongo/data/configdb:/data/configdb